# Generated by Django 3.0.3 on 2023-06-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200425_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='clazz',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.Clazz', verbose_name='班级'),
        ),
    ]
